language: ruby

rvm:
  - 2.2.4

install:
  - sudo apt-get install snapd
  - sudo snap install hugo
  - gem install jekyll

script:
    - cd ..
    - git clone https://thiagohersan:$GHTOKEN@github.com/thiagohersan/atibaia.alab.space.git
    - cd atibaia.alab.space
    - ./deploy.sh

after_script:
  - cd ..
  - rm -rf atibaia.alab.space
