language: ruby

notifications:
  email: false

branches:
  only:
    - master

install:
  - sudo mkdir -p /etc/hugo/bin
  - sudo wget -c https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_0.50_Linux-64bit.tar.gz -O - | sudo tar -xz -C /etc/hugo/bin
  - sudo chmod -R 777 /etc/hugo/bin/
  - PATH=/etc/hugo/bin:$PATH
  - gem install jekyll

script:
    - cd ..
    - git clone https://thiagohersan:$GHTOKEN@github.com/thiagohersan-www/atibaia.alab.space.git
    - cd atibaia.alab.space
    - sed -i -e 's/thiagohersan-hub:/https:\/\/thiagohersan:$GHTOKEN@github.com\//g' .gitmodules
    - ./deploy.sh

after_script:
  - cd ..
  - rm -rf atibaia.alab.space
