language: ruby

rvm:
  - 2.3.1

install:
  - sudo apt-get install snapd
  - sudo snap install hugo
  - PATH=/snap/bin:$PATH
  - gem install jekyll

script:
    - cd ..
    - git clone https://thiagohersan:$GHTOKEN@github.com/thiagohersan-www/atibaia.alab.space.git
    - cd atibaia.alab.space
    - sed -i -e 's/thiagohersan-hub:/https:\/\/thiagohersan:$GHTOKEN@github.com\//g' .gitmodules
    - ./deploy.sh

after_script:
  - cd ..
  - rm -rf atibaia.alab.space
