# Site
title: Festival de Arte e Tecnologia de Atibaia

# URL
url: http://atibaia.alab.space
baseurl: /2017
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4884

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      cover: "/assets/covers/cover00.jpg"
  -
    scope:
      path: ""
      type: "pages"
    values:
      cover: "/assets/covers/cover00.jpg"

# Data
social:
  facebook_url: "https://www.facebook.com/thiago.hersan"
  twitter_url: "https://www.twitter.com/thiagohersan"
  twitter_user: "@thiagohersan"
